// Gotcha B, made mechanical: **a parse is not a run**, and the byte that proves
// it is NUL.
//
// WHY THIS TEST EXISTS, from an incident rather than a theory. `scripts/auto/`
// shipped with a literal NUL byte inside a string sentinel
// (`origin ?? "\0no-origin"`). Every gate this project has was green on it:
//
//   * prettier formatted the file and left the byte alone;
//   * `node --check` parsed it;
//   * the unit tests passed, because the VALUE was correct;
//   * and `git diff` showed nothing unusual.
//
// What it actually broke was SEARCH. ripgrep classifies a file containing NUL
// as binary and skips its contents, so `grep -rn "..." scripts/` reported
// `Binary file ... matches` instead of a line — which reads as a hit with no
// detail rather than as a warning. A codebase-wide search silently stopped
// covering that file, and the project's own gotcha list says only a byte scan
// finds this.
//
// It had a second cost that is worse than the search one: the same sentinel was
// written out TWICE in that file, once in the pool's exclusion key and once in
// `originCount`. Two invisible literals that must match exactly is a partition
// bug nobody can review, because the thing they must agree on cannot be seen.
//
// THE RULE: a control character may appear in source as an ESCAPE (`\u0000`,
// `\x00`, `\0`) — that is legible, greppable, and reviewable — never as a raw
// byte. This test asserts the bytes, so the next one is caught the hour it
// lands rather than the next time somebody greps.
import test from "node:test"
import assert from "node:assert/strict"
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
)

// Directories that are ours to keep clean. Deliberately NOT the whole repo:
// node_modules, .git and jobs/ hold third-party and generated bytes we neither
// own nor review, and a test that fails on those is one people learn to ignore.
const SCANNED = ["scripts", "tests", "docs"]

// Text we author. A .png fixture is legitimately binary; a .mjs is not.
const TEXT_EXT = new Set([
  ".mjs",
  ".js",
  ".cjs",
  ".json",
  ".md",
  ".yaml",
  ".yml",
  ".html",
  ".css",
  ".txt",
])

function* walk(dir) {
  let entries
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true })
  } catch {
    return
  }
  for (const e of entries) {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) {
      if (e.name === "node_modules" || e.name === ".git") continue
      yield* walk(p)
    } else if (TEXT_EXT.has(path.extname(e.name).toLowerCase())) {
      yield p
    }
  }
}

const sources = () => SCANNED.flatMap((d) => [...walk(path.join(ROOT, d))])

test("no source file we author contains a raw NUL byte", () => {
  const offenders = []
  for (const file of sources()) {
    const buf = fs.readFileSync(file)
    const at = buf.indexOf(0)
    if (at >= 0) {
      // The surrounding text, so the failure message names the line rather than
      // an offset nobody can act on.
      const around = buf
        .slice(Math.max(0, at - 60), at + 20)
        .toString("utf8")
        .replace(/\u0000/g, "<NUL>")
      offenders.push(
        `${path.relative(ROOT, file)} at byte ${at}: ...${around}...`,
      )
    }
  }
  assert.deepEqual(
    offenders,
    [],
    "write it as an escape (\\u0000), never as a raw byte — a raw one is " +
      "invisible in every editor and makes ripgrep skip the file's contents",
  )
})

test("the scan actually reads files, and it would catch a planted byte", () => {
  // THE CANARY. A byte scan that silently walked zero files would pass forever
  // and prove nothing — the same "an exit code is not evidence anything ran"
  // failure that npm test's count gate exists for.
  const files = sources()
  assert.ok(
    files.length > 100,
    `expected to scan the tree, walked only ${files.length} files`,
  )
  assert.ok(
    files.some((f) => f.endsWith(path.join("scripts", "auto", "pool.mjs"))),
    "and specifically the file the incident was in",
  )

  const planted = Buffer.from("const key = \u0000no-origin", "utf8")
  assert.ok(planted.indexOf(0) >= 0, "the detector detects")
})

test("the other invisibles that reached this repo are still written as escapes", () => {
  // U+2028/U+2029 are JS line terminators inside what looks like one line, and
  // audit.mjs already carries a written-out note about keeping its OWN source
  // ASCII for that reason. They are legal in the .md prose we write, so this
  // checks the code only.
  const offenders = []
  for (const file of sources()) {
    if (![".mjs", ".js", ".cjs"].includes(path.extname(file))) continue
    const text = fs.readFileSync(file, "utf8")
    const i = text.search(/[\u2028\u2029]/)
    if (i >= 0)
      offenders.push(
        `${path.relative(ROOT, file)} at offset ${i} — write \\u2028 / \\u2029`,
      )
  }
  assert.deepEqual(offenders, [])
})
